### ISSUE TITLE
Hard-coded IPv4 address makes IPv6 usage inconvenient

### ISSUE THREAD

**Issue by CRTified** [yesodweb/wai-handlers#1]
While trying to add [IPv6 support to an application](https://github.com/simonmichael/hledger/issues/1145) that uses `Network.Wai.Handler.Launch.runHostPortUrl`, I noticed that the targeted host is hardcoded to `http://127.0.0.1`. 
This makes adding IPv6 support inconvenient, as it is not possible to open the browser at the correct URL.

The relevant files are:
https://github.com/yesodweb/wai-handlers/blob/master/wai-handler-launch/Network/Wai/Handler/Launch.hs#L182
https://github.com/yesodweb/wai-handlers/blob/master/wai-handler-launch/windows.c#L9

I suspect the easiest way to fix this problem is adding an additional function that also takes a `host` parameter which allows control over the opened URL.

**Comment by snoyberg** [comment]
PR welcome
